- name: Apache installation
  hosts: webservers
  tasks:
          - name: add timezone symlink
            file:
                    src: /usr/share/zoneinfo/Europe/Moscow
                    dest: /etc/localtime
                    state: link
            # ln -snf /usr/share/zoneinfo/Europe/Moscow /etc/localtime

          - name: set timezone
            lineinfile:
                   path: /etc/timezone
                   line: Europe/Moscow
                   create: yes

            #echo Europe/Moscow >> /etc/timezone

          - name: apache2 installation
            package:
                    name: apache2
                    state: present

          - name: install dependencies
            package:
                    name: software-properties-common
                    state: present

          - name: add repository for php8
            apt_repository:
                    repo: ppa:ondrej/php

          - name: installing php8
            ansible.builtin.package:
                    name: php8.0

          - name: installing mysqli
            package:
                    name: php8.0-mysql


          - name: index.php adding
            lineinfile:
                    path: /var/www/html/index.php
                    line: <?php phpinfo();  ?>
                    create: yes

          #  how templates work
          #- name: upload template index.html
          #  template:
          #         src: index.html.j2
          #         dest: "{{ site_dir }}/index.html"
