---
- name: add timezone symlink
  file:
    src: /usr/share/zoneinfo/Europe/Moscow
    dest: /etc/localtime
    state: link

- name: set timezone
  lineinfile:
    path: /etc/timezone
    line: Europe/Moscow
    create: yes

- name: apache2 installation
  package:
    name: apache2
    state: present

- name: install dependencies
  package:
    name: software-properties-common
    state: present

- name: add repository for php8
  apt_repository:
    repo: ppa:ondrej/php

- name: installing php8
  ansible.builtin.package:
    name: php8.0

- name: installing mysqli
  package:
    name: php8.0-mysql

- name: defining index file
  lineinfile:
    path: /etc/apache2/sites-enabled/000-default.conf
    insertafter: 'DocumentRoot /var/www/html'
    line: '        DirectoryIndex index.php'


