---
- name: downloading wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /var/www/wordpress.tar.gz

- name: unzipping archive
  unarchive:
    src: /var/www/wordpress.tar.gz
    dest: /var/www/
    remote_src: yes

- name: delete directory
  file:
    path: /var/www/html
    state: absent

- name: trying to rename wordpress
  copy:
    src: /var/www/wordpress/
    dest: /var/www/html
    remote_src: yes
    directory_mode: yes

- name: deleting archive
  file:
  path: /var/www/wordpress.tar.gz
  state: absent

- name: deleting old dir
  file:
    path: /var/www/wordpress
    state: absent

- name: copying correct wp-config file
  copy:
    src: /home/burnedwitch/ansiblefiles/roles/wphost/files/wp-config.php
    dest: /var/www/html/wp-config.php


