---

- name: zabbix agent installation
  package:
    name: zabbix-agent

- name: adding agent to autoboot
  systemd:
    name: zabbix-agent
    enabled: yes

- name: copying config file
  copy:
    src: ./roles/z-agent/files/zabbix-agent.conf
    dest: /etc/zabbix/zabbix_agentd.conf.d/
    
- name: restarting service
  systemd:
    name: zabbix_agent
    state: restarted

