- name: mysql server default installation
  package: 
    name: mysql-server-8.0
    state: present

- name: adding to autoreboot
  systemd:
    name: mysql
    enabled: yes

- name: mysql db adding
  community.mysql.mysql_db:
    name: {{ base_name }}
    state: present

- name: mysql user adding
  community.mysql.mysql_user:
    name: {{ user_name }}
    password: {{ passwd }}
    priv: '{{ base_name }}.*:ALL'
    state: present
