- name: mysql server default installation
  package: 
    name: mysql-server-8.0
    state: present

- name: adding to autoreboot
  systemd:
    name: mysql
    enabled: yes

- name: python installing for ansible community module
  package:
    name: python3
    state: present

- name: pip installing
  package:
    name: pip
    state: present

- name: pymysql  installing
  pip:
    name: PyMySQL

    #- name: trying to change root passwd
    #  community.mysql.mysql_user:
    #    name: root
    #    password: A11A11
    #    priv: '*.*:ALL'

- name: waiting time
  pause:
          prompt: "Here we're waiting for you to set mysql root password: ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY 'A11A11';"


- name: copying .my.cnf
  copy:
    src: ./roles/mysql/files/.my.cnf
    dest: /root/.my.cnf

- name: mysql db adding
  community.mysql.mysql_db:
    login_user: root
    login_password: A11A11
    name: "{{ base_name }}"
    state: present


- name: mysql user adding
  community.mysql.mysql_user:
    name: "{{ user_name }}"
    password: "{{ user_passwd }}"
    priv: '{{ base_name }}.*:ALL'
    state: present


