---
- name: add timezone symlink
  file:
    src: /usr/share/zoneinfo/Europe/Moscow
    dest: /etc/localtime
    state: link

- name: set timezone
  lineinfile:
    path: /etc/timezone
    line: Europe/Moscow
    create: yes

- name:  creating /var/www directory
  file:
    path: /var/www
    state: directory
    mode: '0755'

- name: downloading wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /var/www/wordpress.tar.gz

- name: unzipping archive
  unarchive:
    src: /var/www/wordpress.tar.gz
    dest: /var/www/
    remote_src: yes

- name: copying correct wp-config file
  copy:
    src: ./roles/web-docker/files/wp-config.php
    dest: /var/www/wordpress/wp-config.php


- name: installing containerd
  apt:
    deb: https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/containerd.io_1.4.9-1_amd64.deb

- name: installing docker-cli .deb
  apt:
    deb: https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/docker-ce-cli_20.10.8~3-0~ubuntu-focal_amd64.deb


- name: installing docker .deb
  apt:
    deb: https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/docker-ce_20.10.8~3-0~ubuntu-focal_amd64.deb

- name: downloading docker compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.0.1/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: starting docker 
  service:
    name: docker
    state: started

- name: making db directory
  file:
    path: /var/www/database/
    state: directory

- name: and docker directory
  file:
    path: /etc/docker
    state: directory


- name: copying compose file
  copy:
    src: ./roles/web-docker/files/docker-compose.yml
    dest: /etc/docker/docker-compose.yml

- name: copying unit file
  copy:
    src: ./roles/web-docker/files/unitfile.service
    dest: /etc/systemd/system/docker-container.service
    mode: '0644'

- name: enable service
  systemd:
    name: docker-container
    enabled: yes

- name: starting service
  systemd:
    name: docker-container
    state: restarted
