# my global config
global:
  scrape_interval: 15s 
  evaluation_interval: 15s 
  # scrape_timeout is set to the global default (10s).


alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093


# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alerting_rules.yml"
  # - "second_rules.yml"


# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
#
#
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]


  - job_name: "node"
    static_configs:
      - targets: ["localhost:9100"]


  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:

      - targets:
        - https://www.blizzard.com/en-us/
        - https://playheartstone.com/en-us
        - https://worldofwarcraft.com/ru-ru/
        labels:
          site_name: blizzard

      - targets:          
        - https://yandex.ru
        labels:
          site_name: yandex.ru

    relabel_configs:
        # parameter 'target' for blackbox is assigned value in __address__ ('target' from static_configs)
      - source_labels: [__address__]
        target_label: __param_target
        # label 'instance' is assigned value from parameter 'target' — just to make it more clear
      - source_labels: [__param_target]
        target_label: instance
        # 'target' of static_configs become blackbox address
      - target_label: __address__
        replacement: localhost:9115
