---
# uncomment this for the first-time use
#- name: apt update
#  apt:
#    update_cache: yes

# this too
#- name: apt upgrade
#  apt:
#    upgrade: yes

- name: downloading prometheus binaries
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.32.0-beta.0/prometheus-2.32.0-beta.0.linux-amd64.tar.gz
    dest: /root/prometheus.tar.gz

- name: unzipping archive
  unarchive:
    src: /root/prometheus.tar.gz
    dest: /root
    remote_src: yes

- name: making correct directory
  file:
    path: /etc/prometheus
    state: directory

- name: copying files
  copy:
    src: /root/prometheus-2.32.0-beta.0.linux-amd64/
    dest: /etc/prometheus
    remote_src: yes
    directory_mode: yes

- name: copying config file
  copy:
    src: ./roles/prometheus/files/prometheus.yml
    dest: /etc/prometheus/prometheus.yml

- name: copying unit file
  copy:
    src: ./roles/prometheus/files/unitfile.service
    dest: /etc/systemd/system/prometheus.service
    mode: '0644'

- name: copying alerting rules file
  copy:
    src: ./roles/prometheus/files/alerting_rules.yml
    dest: /etc/prometheus/alerting_rules.yml

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: enable service
  systemd:
    name: prometheus
    enabled: yes

- name: starting service
  systemd:
    name: prometheus
    state: restarted
    

