---
#- name: Zabbix repo downloading
#  get_url:
#    url: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb
#    dest: /home/ubuntu/

- name: packge installation
  apt:
#    deb: /home/ubuntu/zabbix-release_5.0-1+focal_all.deb
    deb: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb

- name: apt upgrade =)
  apt:
    update_cache: yes

- name: zabbix-server installation
  package:
    name: zabbix-server-mysql
    state: present

- name: ... and zabbix frontend
  package:
    name: zabbix-frontend-php

